"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = "django-insecure-v8l=sqil0el&+y6zb)l_a%w5b401*nycpi2fsky!u57n_jo@eq"
DEBUG = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "bootstrap5",
    "tailwind",
    "django_browser_reload",
    "app_theme",
    "app_main",
    "app_todo",
    "app_user",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",  # 📝 внутренняя
        # "BACKEND": "django.template.backends.jinja2.Jinja2",        # 📝 Jinja2
        "DIRS": [os.path.join(BASE_DIR, 'templates'), ],  # 📁🔎 путь поиска шаблонов /project/templates/*
        "APP_DIRS": True,  # 📁🔎 разрешить поиск шаблонов внутри папок приложений
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",  # 🐞 debug, sql_queries
                "django.template.context_processors.request",  # 📧 request object
                "django.contrib.auth.context_processors.auth",  # 👤 user & permissons
                "django.contrib.messages.context_processors.messages",  # 💬 messages
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
MEDIA_URL = "/media/"  # URL для медии в шаблонах
STATIC_URL = "/static/"  # URL для статики в шаблонах
# пустая папка, сюда будет собирать статику collectstatic
MEDIA_ROOT = os.path.join(PROJECT_ROOT, "media")
STATIC_ROOT = os.path.join(PROJECT_ROOT, "static")

STATICFILES_DIRS = (os.path.join(PROJECT_ROOT, "assets"),)


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "app_user.CustomUser"


# WindTail
TAILWIND_APP_NAME = "app_theme"
INTERNAL_IPS = ["127.0.0.1"]


#
ALLOWED_HOSTS = []
INTERNAL_IPS = [
    "127.0.0.1",
]
